INSERT INTO ACCOUNT (FIRSTNAME , LASTNAME ) VALUES ('Scott', 'Smith');
INSERT INTO ACCOUNT (ACCOUNTNUMBER , FIRSTNAME , LASTNAME ) VALUES (56, 'Jack', 'Smith');
INSERT INTO ACCOUNT (ACCOUNTNUMBER , FIRSTNAME , LASTNAME ) VALUES (77, 'Help', 'Smith');
INSERT INTO ACCOUNT (ACCOUNTNUMBER , FIRSTNAME , LASTNAME ) VALUES (77, 'Lucy', 'Jenkins');
INSERT INTO ACCOUNT (ACCOUNTNUMBER , FIRSTNAME , LASTNAME ) VALUES (77, 'Me', 'Smith');
INSERT INTO ACCOUNT (ACCOUNTNUMBER , FIRSTNAME , LASTNAME ) VALUES (77, 'Me', 'Smith');
INSERT INTO ACCOUNT (ACCOUNTNUMBER , FIRSTNAME , LASTNAME ) VALUES (77, 'Me', 'Smith');

SELECT a FROM ACCOUNT a WHERE a.LASTNAME = "Smith";